[[에러]]가 발생했을 때 프로그램 전체가 멈추지 않고 에러에 대처하기 위한 기능이다.
# try
에러가 발생할 수 있는 코드를 넣는 공간이다.
# catch
에러가 발생하면 실행되어야하는 코드를 넣는 공간이다.
# finally
에러가 발생하든 발생하지 않든 실행되어야 하는 코드를 넣는 공간이다.
return이 발생해도 무조건 실행된다.
# throw
에러를 발생시키는 코드다.